#!/bin/bash

#----------------------------------------------
# Select the matrix list file name
#----------------------------------------------
LIST=matrix_lists/matrix_list_160.txt
#----------------------------------------------

#----------------------------------------------
# Select the matrix format. Avail:
#    [*] csr_base
#    [*] csr_vec
#    [*] csr_autovec
#    [*] csr_highway
#    [*] sellp_vec
#    [*] sellp_autovec
#    [*] sellp_highway
#----------------------------------------------
MODE=csr_base
#----------------------------------------------

#----------------------------------------------
# Select the output path
#----------------------------------------------
OUT=output
#----------------------------------------------

export OMP_NUM_THREADS=1

BIND="taskset -c 0 "

mkdir -p $OUT

n=$(ls -l $OUT | wc -l)

$BIND ./build/spmv "$MODE" "$LIST" "$OUT/$n.csv"

